const V=[["inicio","Início"],["saude","Minha saúde"],["prevencao","Prevenção"],["sexual","Saúde sexual"],["apoio","Saúde mental"],["trans","Mulheres trans"],["servicos","Serviços"],["conteudos","Conteúdos"]];
const L={ms:["Ministério da Saúde","https://www.gov.br/saude/pt-br"],colo:["INCA — Câncer do colo do útero","https://www.gov.br/inca/pt-br/assuntos/cancer/tipos/colo-do-utero"],rast:["MS — Rastreamento do câncer do colo do útero","https://www.gov.br/saude/pt-br/assuntos/pcdt/r/rastreamento-cancer-do-colo-do-utero/view"],endo:["MS — Endometriose","https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/e/endometriose"],l180:["Ligue 180 — Ministério das Mulheres","https://www.gov.br/mulheres/pt-br/ligue180"],rede:["Painel da Rede de Atendimento","https://www.gov.br/mulheres/pt-br/ligue180/painel-da-rede-de-atendimento"],dig:["Programa Dignidade Menstrual","https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/cartilhas/2024/dignidademenstrual"],sm:["MS — Saúde da Mulher","https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-mulher"],feb:["Febrasgo — campanhas informativas","https://www.febrasgo.org.br/campanhas-informativas/"],iff:["Fiocruz IFF — perguntas frequentes","https://portaldeboaspraticas.iff.fiocruz.br/faq-perguntas-frequentes/"],oms:["OMS — saúde da mulher","https://www.who.int/health-topics/women-s-health"]};
const CAT={prev:"Prevenção",sex:"Saúde sexual",men:"Saúde mental e proteção",trans:"Mulheres trans"};
const ART=[
{id:"colo",c:"prev",t:"Câncer do colo do útero e rastreamento",i:"Quase sempre começa com infecção persistente pelo HPV e costuma evoluir devagar, o que permite detectar alterações antes de virarem câncer.",s:[["Rastreamento","O exame preventivo (citopatológico) é indicado a mulheres e pessoas com colo do útero, em geral de 25 a 64 anos, que já tiveram relações sexuais. Confira a frequência atual no protocolo do Ministério da Saúde."],["Quando procurar atendimento","Sangramento fora da menstruação ou após a relação, corrimento diferente do habitual ou dor pélvica persistente pedem consulta na UBS, mesmo com o preventivo em dia."]],f:["colo","rast"],x:[["Cadastrar exame","saude","exame"]]},
{id:"endo",c:"prev",t:"Endometriose",i:"Doença crônica em que um tecido parecido com o que reveste o útero cresce em outros locais, como ovários e pelve.",s:[["Sinais mais comuns","Cólica menstrual muito forte, dor pélvica, dor na relação sexual, alterações intestinais ou urinárias no período menstrual e dificuldade para engravidar. Nem toda cólica forte é endometriose; só a avaliação profissional confirma."],["O que fazer","Anote no Diário quando a dor aparece e o quanto atrapalha a rotina, e leve à consulta na UBS ou com ginecologista."]],f:["endo"],x:[["Abrir o Diário","saude","diario"]]},
{id:"cardio",c:"prev",t:"Coração e circulação",i:"Fatores de risco como pressão alta e diabetes podem ser acompanhados na atenção básica.",s:[["Cuidados gerais","Medir pressão e glicemia com regularidade na UBS, manter atividade física e alimentação variada e evitar cigarro e excesso de álcool."],["Quando procurar atendimento","Dor ou aperto no peito, falta de ar súbita, fraqueza ou formigamento de um lado do corpo, dificuldade para falar ou boca torta: ligue 192 imediatamente."]],f:["ms"]},
{id:"osseo",c:"prev",t:"Saúde dos ossos",i:"Os ossos perdem massa ao longo da vida, principalmente após a menopausa, e fraturas podem afetar a autonomia.",s:[["Cuidados gerais","Atividade física com impacto e fortalecimento muscular, alimentos com cálcio, sol moderado e evitar cigarro e excesso de álcool."],["Acompanhamento","Quem teve fraturas, usa alguns medicamentos por muito tempo ou tem histórico familiar deve conversar na UBS sobre exames. Não tome suplementos sem orientação."]],f:["ms"]},
{id:"dig",c:"prev",t:"Dignidade menstrual",i:"Programa federal que busca garantir acesso a absorventes e informação sobre menstruação a quem não tem condições de comprar.",s:[["Como funciona","Os critérios e o passo a passo podem mudar; consulte a cartilha oficial antes de se cadastrar."],["Quando procurar atendimento","Sangramento muito intenso, com coágulos grandes ou que encharca o absorvente em pouco tempo, ou dor que impede a rotina, merece avaliação na UBS."]],f:["dig"]},
{id:"ists",c:"sex",t:"ISTs: prevenção, testagem e tratamento",i:"HIV, sífilis, HPV, hepatites virais e gonorreia muitas vezes não dão sintomas. Testar faz parte do cuidado, sem julgamento.",s:[["Prevenção combinada","Preservativo, testagem regular, vacinas (HPV e hepatite B) e, quando indicado, PrEP e PEP, oferecidas pelo SUS contra o HIV. A PEP deve começar em até 72 horas após a exposição."],["Testagem","Testes rápidos de HIV, sífilis e hepatites B e C são gratuitos nas UBS e serviços de testagem, com resultado na hora."],["Cada infecção","HIV: o tratamento no SUS permite viver bem e, com carga viral indetectável, não transmitir. Sífilis: tem cura com antibiótico e o parceiro também precisa tratar. Hepatite B: há vacina. Hepatite C: tem tratamento com cura. Gonorreia: tratável com antibiótico prescrito. HPV: comum; a vacina previne e o preventivo detecta lesões."],["Quando procurar atendimento","Corrimento, ardência ao urinar, feridas, verrugas, dor pélvica ou exposição de risco. Não se automedique."]],f:["ms","sm"],x:[["Encontrar serviço de testagem","servicos"]]},
{id:"contra",c:"sex",t:"Contracepção e consentimento",i:"Decidir se e quando engravidar e ter relações seguras e desejadas é parte da saúde sexual.",s:[["Métodos","O SUS oferece diferentes métodos, como preservativos, pílulas, injetáveis e DIU. A escolha é feita com a equipe da UBS. Só o preservativo também protege contra ISTs."],["Consentimento","É um sim livre e claro, a cada relação e prática, que pode ser retirado a qualquer momento. Silêncio, medo, sono, efeito de álcool ou pressão não são consentimento."],["Relações saudáveis","Há respeito às escolhas, conversa sem ameaça e liberdade para dizer não. Sinais de controle ou medo merecem atenção: veja Saúde mental e proteção."]],f:["sm","l180"]},
{id:"wsw",c:"sex",t:"Mulheres que se relacionam com mulheres",i:"Também podem ter ISTs e precisam de cuidado ginecológico regular.",s:[["Mitos","Não existe risco zero: HPV, herpes, sífilis e outras infecções passam por contato entre mucosas, pele e fluidos, inclusive por brinquedos compartilhados. O preventivo é indicado do mesmo jeito."],["Prevenção","Barreiras de látex ou filme plástico no sexo oral, luvas, preservativo trocado entre brinquedos e testagem regular."],["Acolhimento","Você não precisa esconder sua orientação sexual para ser atendida. Se sofrer discriminação, registre na Ouvidoria do SUS (136)."]],f:["ms"]},
{id:"emo",c:"men",t:"Ansiedade, estresse e sobrecarga",i:"Sentir-se sobrecarregada ou ansiosa é frequente e não é fraqueza. Muitas mulheres acumulam trabalho, casa e cuidado com outras pessoas.",s:[["Sinais para observar","Preocupação constante, insônia, irritação, choro fácil, isolamento, perda de interesse, sensação de não dar conta, mudanças no apetite."],["Pequenos cuidados","Conversar com alguém de confiança, fazer pausas, manter sono regular, mexer o corpo e pedir ajuda na divisão de tarefas. Não substituem acompanhamento quando o sofrimento persiste."],["Quando procurar atendimento","Se dura semanas ou atrapalha o dia a dia, procure a UBS, que pode encaminhar ao CAPS. Apoio emocional imediato: 188 (CVV). Risco de vida: 192."]],f:["ms"],x:[["Registrar no Diário","saude","diario"]]},
{id:"viol",c:"men",t:"Tipos de violência e rede de apoio",i:"Violência não é só agressão física. A Lei Maria da Penha reconhece cinco formas, e nenhuma é culpa de quem a sofre.",s:[["Formas de violência","Física: agressões. Psicológica: humilhação, ameaça, controle, isolamento. Sexual: ato sexual sem consentimento, inclusive no casamento. Patrimonial: destruir ou reter documentos, dinheiro ou bens. Moral: calúnia, difamação e injúria. Há ainda a violência digital, como perseguição, vigilância e divulgação de imagens sem autorização."],["Como buscar ajuda","Ligue 180 (gratuito, orienta e encaminha), 190 em perigo imediato, Delegacia da Mulher ou qualquer delegacia, CRAS/CREAS e UBS. É possível pedir medidas protetivas."],["Sinais de alerta","Medo do parceiro, controle de roupa, celular e dinheiro, afastamento de amigos e família, ameaças. Se puder, combine um plano de segurança com alguém de confiança."]],f:["l180","rede"]},
{id:"trans1",c:"trans",t:"Acesso à saúde e acompanhamento",i:"Mulheres trans têm direito a atendimento em todos os serviços do SUS, com respeito ao nome social e sem discriminação.",s:[["Direitos","O uso do nome social é garantido no SUS. Em caso de constrangimento ou recusa, registre na Ouvidoria do SUS (136)."],["Hormônios e afirmação de gênero","O SUS tem o Processo Transexualizador, com equipe multiprofissional. A oferta varia por estado e cidade: confirme na secretaria de saúde. Hormônios só devem ser usados com acompanhamento profissional; a ELLA não indica medicamentos nem doses."],["Quando procurar atendimento","Se já usa hormônios sem acompanhamento, procure a UBS para orientação segura, sem julgamento."]],f:["ms"]},
{id:"trans2",c:"trans",t:"Prevenção e cuidado ginecológico",i:"As necessidades de prevenção dependem do corpo e das práticas sexuais de cada pessoa, não só da identidade de gênero.",s:[["ISTs e vacinas","Testagem regular de HIV, sífilis e hepatites, preservativo, vacinas do calendário e PrEP/PEP, quando indicadas, estão no SUS. Pergunte na UBS quais grupos têm acesso à vacina HPV."],["Acompanhamento","Quem tem colo do útero mantém o rastreamento. Quem fez cirurgia de afirmação deve conversar com a equipe sobre cuidados específicos. A próstata permanece em quem não a retirou: pergunte ao profissional sobre acompanhamento."]],f:["ms","sm"],x:[["Encontrar serviço","servicos"]]}
];
const DEEP={
colo:{i:"Quase sempre começa com uma infecção persistente pelo HPV e evolui devagar, por isso dá tempo de encontrar e tratar alterações antes de virarem câncer. Aqui você entende tudo, do exame ao resultado.",s:[
["O que é e como começa","O câncer do colo do útero surge nas células da parte de baixo do útero, que se abre na vagina. Quase todos os casos estão ligados a certos tipos de HPV, um vírus muito comum transmitido pelo contato sexual. Na maioria das vezes o corpo elimina o vírus sozinho. Só quando ele permanece por anos as células podem mudar e formar lesões pré-câncer. Esse caminho é lento, e é por isso que o exame preventivo funciona: encontra a lesão antes de ela virar câncer."],
["Quem deve fazer","Mulheres e pessoas com colo do útero, de 25 a 64 anos, que já tiveram relação sexual, mesmo que:\n• não tenham nenhum sintoma;\n• se relacionem com mulheres;\n• sejam pessoas trans com colo do útero;\n• estejam na menopausa;\n• tenham tomado a vacina do HPV (ela não protege contra todos os tipos).\nSe retirou o útero por inteiro, pergunte à equipe se ainda precisa."],
["Como se preparar","Nas 48 horas antes, evite relação sexual, ducha vaginal e cremes, óvulos ou medicamentos vaginais, a menos que o profissional tenha indicado. Não faça menstruada: espere cerca de cinco dias depois que o sangramento terminar. Pode ser feito na gravidez, com orientação da equipe. Se não conseguiu seguir algum cuidado, vá mesmo assim e avise."],
["Como é o exame, passo a passo","1. Conversa rápida sobre ciclo, método contraceptivo e último exame.\n2. Você retira a roupa da cintura para baixo, com privacidade, e deita na maca.\n3. O profissional coloca o espéculo, um instrumento que abre a vagina com delicadeza.\n4. Com espátula e escovinha, coleta células do colo do útero.\n5. Retira o espéculo. Tudo leva poucos minutos.\nPode incomodar, mas não deve doer forte. Você pode pedir que explique cada passo, ir mais devagar ou parar. Um leve sangramento depois é possível."],
["Com que frequência","Pelo protocolo em vigor, repete-se o primeiro exame depois de um ano; se os dois primeiros forem normais, o intervalo passa a ser de três anos. As diretrizes são atualizadas de tempos em tempos (inclusive com discussão do teste de DNA-HPV), então confirme a rotina atual na UBS ou no protocolo do Ministério da Saúde."],
["Entendendo o resultado","O laudo traz siglas e termos técnicos. Quem interpreta e decide o próximo passo é a equipe de saúde. Em geral:\n• Normal ou com inflamação: segue a rotina de rastreamento.\n• Alteração nas células: pode ser pedido repetir o exame, fazer colposcopia (olhar o colo com uma lupa) e, se necessário, biópsia.\n• Amostra insatisfatória: o material não bastou e o exame precisa ser repetido.\nAlteração não significa câncer: a maioria são lesões que podem ser acompanhadas ou tratadas. Sempre volte para buscar o resultado."],
["Se encontrarem uma lesão","Lesões precursoras podem ser tratadas com procedimentos simples, em geral ambulatoriais, que retiram a área alterada. Quando o câncer é descoberto cedo, as chances de tratamento bem-sucedido são maiores. A UBS encaminha para os serviços de referência. Se a espera for longa demais, registre na Ouvidoria do SUS (136)."],
["Como reduzir o risco","Vacina contra o HPV (oferecida no SUS a públicos definidos pelo Ministério, como adolescentes de 9 a 14 anos; confira os grupos atuais na UBS), preservativo, preventivo em dia e não fumar, pois o cigarro aumenta o risco."],
["Dúvidas comuns","Nunca fiz e já passei dos 25: nunca é tarde até os 64; procure a UBS. Tenho vergonha: a equipe faz isso todos os dias, e você pode pedir privacidade e explicações. Tenho medo de dor: avise antes e durante o exame. Nunca tive relação sexual: em geral o exame é indicado a quem já iniciou a vida sexual."],
["Quando procurar atendimento","Sangramento fora da menstruação, depois da relação ou depois da menopausa, corrimento com mau cheiro ou dor pélvica persistente pedem consulta na UBS, mesmo com o preventivo em dia."]]},
ists:{i:"HIV, sífilis, hepatites virais, gonorreia e HPV muitas vezes não dão sintomas. Por isso testar faz parte do cuidado, sem culpa e sem julgamento. A maioria tem prevenção, tratamento ou cura no SUS.",s:[
["Por que testar, mesmo sem sintomas","Muitas infecções ficam silenciosas por meses ou anos e, sem tratamento, podem causar problemas sérios, inclusive na gravidez. Descobrir cedo facilita o tratamento e protege você e as outras pessoas. Fazer teste não significa que você fez algo errado."],
["HIV","É o vírus que ataca as defesas do corpo; sem tratamento, pode evoluir para a aids. O tratamento gratuito do SUS permite viver bem e, com carga viral indetectável mantida, a pessoa não transmite o HIV pelo sexo. Gestantes em tratamento reduzem muito a chance de passar o vírus ao bebê. HIV não passa por abraço, beijo, talher, suor nem vaso sanitário."],
["Sífilis","Começa, em geral, com uma ferida que não dói, na vagina, no colo do útero, no ânus ou na boca, e que some sozinha, dando a falsa impressão de cura. Depois podem surgir manchas na pele, inclusive nas palmas das mãos e nas plantas dos pés, e febre. Sem tratamento pode causar problemas graves anos depois e passar para o bebê na gravidez. Tem cura com penicilina, e a parceria também precisa tratar. É possível ter sífilis de novo, então continue se testando."],
["Hepatites virais","Hepatite A: transmitida por água e alimentos contaminados; há vacina. Hepatite B: passa por sexo e sangue; a vacina, em três doses, está disponível no SUS. Hepatite C: passa principalmente por sangue; não há vacina, mas o tratamento atual cura a maioria dos casos. Muitas hepatites não dão sintomas."],
["Gonorreia e clamídia","Muitas mulheres não sentem nada. Quando há sintomas: corrimento diferente, ardência ao urinar, dor pélvica ou sangramento entre as menstruações. Sem tratamento podem causar inflamação pélvica, dor crônica, dificuldade para engravidar e gravidez fora do útero. O tratamento é com antibiótico prescrito; a parceria também deve ser tratada. Não use sobras de antibiótico."],
["HPV e herpes genital","HPV: muito comum; pode causar verrugas e, em alguns tipos, lesões no colo do útero. A vacina previne e o preventivo detecta alterações. Herpes: feridas dolorosas que voltam de tempos em tempos; não tem cura, mas o tratamento alivia e reduz as crises. Pode haver transmissão mesmo sem feridas visíveis."],
["Prevenção combinada","Preservativo em todas as relações, vacinas (HPV e hepatite B), testagem regular e, para HIV, PrEP (comprimido tomado antes da exposição, por quem tem maior chance de se expor, com avaliação) e PEP (tratamento iniciado em até 72 horas após a exposição e mantido por 28 dias). Quanto antes a PEP, melhor: vá ao serviço de saúde imediatamente."],
["Testagem na prática","Peça na UBS os testes rápidos de HIV, sífilis e hepatites B e C: são gratuitos, saem em cerca de meia hora e vêm com orientação e sigilo. Teste depois de nova parceria ou exposição de risco. Se o resultado for negativo muito pouco tempo depois da exposição, a equipe pode pedir nova testagem. Com sintomas, o profissional avalia e pode coletar material."],
["Quando procurar atendimento","Corrimento ou cheiro diferente, ardência ao urinar, feridas, verrugas, dor pélvica ou na relação, ou qualquer exposição de risco. Não se automedique."]]},
viol:{i:"Violência contra a mulher não é só agressão física, e a culpa nunca é de quem a sofre. Este conteúdo explica como reconhecer, o que fazer e onde buscar ajuda.",s:[
["Formas de violência","Segundo a Lei Maria da Penha:\n• Física: bater, empurrar, sufocar, machucar.\n• Psicológica: humilhar, ameaçar, controlar, isolar, fazer duvidar da própria memória.\n• Sexual: qualquer ato sexual sem consentimento, inclusive dentro do casamento ou namoro.\n• Patrimonial: destruir ou reter documentos, dinheiro, bens ou ferramentas de trabalho.\n• Moral: calúnia, difamação e injúria.\nHá também a violência digital: vigilância do celular, perseguição, ameaças e divulgação de imagens íntimas sem autorização."],
["O ciclo da violência","Muitos casos seguem um padrão: a tensão aumenta, vem a agressão, depois o arrependimento e promessas de mudança, e então tudo recomeça, em geral com mais frequência e gravidade. Acreditar nas promessas não é ingenuidade: é parte do ciclo. Buscar ajuda cedo interrompe o padrão."],
["Sinais de alerta","Medo do parceiro ou da parceira; controle de roupa, celular, dinheiro e amizades; ciúme extremo; humilhações; ameaças; afastamento de família e amigos; pedir desculpas o tempo todo. Se você reconhece alguns, procure apoio, mesmo que nunca tenha havido agressão física."],
["Violência sexual: o que fazer","Procure um serviço de saúde o quanto antes. O atendimento é um direito e não depende de boletim de ocorrência. Em até 72 horas é possível receber medicação para prevenir HIV e outras infecções, e a contracepção de emergência deve ser tomada o mais cedo possível. Se conseguir, evite banho e troca de roupa antes do atendimento para preservar provas, mas a sua saúde vem primeiro. Em casos previstos em lei, há direito a interrupção da gravidez."],
["Medidas protetivas e denúncia","Você pode denunciar na Delegacia da Mulher ou em qualquer delegacia e pedir medidas protetivas, como afastamento do agressor e proibição de contato. A Justiça deve decidir o pedido em até 48 horas. A proteção da lei também vale para mulheres trans, conforme decisões do STJ. Também é possível denunciar pelo Ligue 180."],
["Plano de segurança","Combine com alguém de confiança um sinal de pedido de ajuda. Deixe em local seguro uma bolsa com documentos, dinheiro, chaves, medicamentos e cópias de provas. Guarde mensagens, prints e laudos. Saiba o caminho até um local seguro. Apague o histórico do navegador se alguém controla seu aparelho. Em perigo imediato, ligue 190."],
["Feminicídio","É o assassinato de uma mulher por razões de gênero, como em contexto de violência doméstica ou por menosprezo à condição de mulher. É crime hediondo e costuma ser precedido por outras violências. Sinais de maior risco: ameaça de morte, acesso a arma, perseguição, ciúme extremo e separação recente. Nesses casos, busque proteção imediatamente."],
["Se uma amiga sofre violência","Escute sem julgar, acredite, não pressione nem diga o que ela deve fazer, ofereça ajuda concreta e respeite o tempo dela. Qualquer pessoa pode ligar para o Ligue 180 para orientação ou denúncia."],
["Cuidando da saúde mental depois","Culpa, medo, vergonha, insônia e ansiedade são reações comuns, e não sinal de fraqueza. Procure a UBS ou o CAPS. Para conversar agora, ligue 188 (CVV)."]]}
};
ART.forEach(a=>DEEP[a.id]&&Object.assign(a,DEEP[a.id]));
const UPD="30/09/2026";
const D={it:[],cy:[],dia:[],q:{}};
try{const s=JSON.parse(localStorage.getItem("ella")||"{}");Object.assign(D,s);if(s.ev){D.it=D.it.concat(s.ev.map(e=>({id:e.id,k:["exame","consulta","vacina"].includes(e.k.toLowerCase())?e.k.toLowerCase():"lembrete",t:e.t,d:e.d,n:e.n,done:0})));delete D.ev}}catch(e){}
const save=()=>{try{localStorage.setItem("ella",JSON.stringify(D))}catch(e){}};
const $=i=>document.getElementById(i);
const fmt=d=>new Date(d+"T12:00").toLocaleDateString("pt-BR");
const esc=s=>String(s==null?"":s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const iso=d=>d.toISOString().slice(0,10),today=()=>iso(new Date());
const add=(s,n)=>{const d=new Date(s+"T12:00");d.setDate(d.getDate()+n);return iso(d)};
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("on");clearTimeout(toast.h);toast.h=setTimeout(()=>t.classList.remove("on"),2800)}
let CUR="inicio",PREV="inicio",TAB="painel",ED=null,ED2=null,CAL={v:"m",r:today()};
function go(id,sub){if(id!==CUR&&id!=="artigo")PREV=id;CUR=id;
document.querySelectorAll(".view").forEach(v=>v.classList.toggle("on",v.id===id));
document.querySelectorAll("#nav button").forEach(b=>b.setAttribute("aria-current",b.dataset.v===id));
if(id==="saude")tab(sub||TAB);if(id==="conteudos")rLib();if(id==="referencias")rRef();if(id==="inicio")rHome();scrollTo(0,0)}
function emblem(){let d="";for(let i=0;i<12;i++){const a=i*Math.PI/6;d+=`<circle cx="${(32+25*Math.cos(a)).toFixed(1)}" cy="${(32+25*Math.sin(a)).toFixed(1)}" r="2.3"/>`}
return `<svg class="emb" viewBox="0 0 64 64" role="img" aria-label="Símbolo da Imperatriz: coroa de doze estrelas e o signo de Vênus" fill="currentColor">${d}<circle cx="32" cy="27" r="9" fill="none" stroke="currentColor" stroke-width="2.4"/><path d="M32 36v14M26 43h12" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" fill="none"/></svg>`}
/* ---- Conteúdos ---- */
const cards=(c,q)=>ART.filter(a=>(!c||a.c===c)&&(!q||(a.t+a.i).toLowerCase().includes(q))).map(a=>`<button class="card go" onclick="art('${a.id}')"><span class="pill">${CAT[a.c]}</span><h3>${a.t}</h3><p>${a.i}</p></button>`).join("")||"<p>Nenhum conteúdo encontrado. Tente outra palavra.</p>";
let LC="";
function rLib(){const q=$("lq").value.trim().toLowerCase();
$("lch").innerHTML=[["","Todos"],...Object.entries(CAT)].map(x=>`<button class="chip" aria-pressed="${LC===x[0]}" onclick="LC='${x[0]}';rLib()">${x[1]}</button>`).join("");
$("lres").innerHTML=cards(LC,q)+(!LC||LC==="prev"?`<button class="card go" onclick="go('gestacao')"><span class="pill">Prevenção</span><h3>Gestação e perda gestacional</h3><p>Tipos de abortamento, sinais de alerta, cuidados e o que a lei permite.</p></button>`:"")}
function art(id){const a=ART.find(x=>x.id===id);
$("artc").innerHTML=`<button class="lk" onclick="go(PREV)">← Voltar</button><span class="pill">${CAT[a.c]}</span><h2>${a.t}</h2><p class="lead">${a.i}</p>`+a.s.map((s,i)=>`<details ${i<1?"open":""}><summary>${s[0]}</summary><p>${s[1].replace(/\n/g,"<br>")}</p></details>`).join("")+
`<div class="row acts">${a.f.map(k=>`<a class="btn" href="${L[k][1]}" target="_blank" rel="noopener">Consultar fonte oficial: ${L[k][0]}</a>`).join("")}</div><div class="row acts">${(a.x||[]).concat([["Encontrar um serviço","servicos"],["Ver todas as referências","referencias"]]).map(x=>`<button class="btn alt" onclick="go('${x[1]}'${x[2]?`,'${x[2]}'`:""})">${x[0]}</button>`).join("")}</div><p class="note">Atualizado em ${UPD}. Conteúdo educativo em revisão: confirme sempre na fonte oficial. Não substitui avaliação profissional.</p>`;
go("artigo")}
function rRef(){const u={};ART.forEach(a=>a.f.forEach(k=>(u[k]=u[k]||[]).push(a.t)));
$("refl").innerHTML=Object.keys(L).map(k=>`<li><div><b>${L[k][0]}</b><small>${u[k]?"Usada em: "+u[k].join("; "):"Fonte geral do projeto"}</small></div><a class="btn alt" href="${L[k][1]}" target="_blank" rel="noopener">Abrir</a></li>`).join("")}
/* ---- Início ---- */
function rHome(){const p=D.it.filter(e=>!e.done&&e.k!=="documento"&&e.d>=today()).sort((a,b)=>a.d.localeCompare(b.d)).slice(0,3);
$("prox").innerHTML=p.length?p.map(liIt).join(""):"<li>Nada agendado ainda. <button class='lk' onclick=\"go('saude','calendario')\">Adicionar ao calendário</button></li>"}
/* ---- Minha saúde ---- */
const TABS=[["painel","Painel"],["calendario","Calendário"],["exame","Exames"],["consulta","Consultas"],["vacina","Vacinas"],["lembrete","Lembretes"],["diario","Diário"],["ciclo","Ciclo"],["documento","Documentos"],["resumo","Resumo para consulta"]];
const KN={exame:"Exame",consulta:"Consulta",vacina:"Vacina",lembrete:"Lembrete",documento:"Documento"};
function tab(t){TAB=t;$("stabs").innerHTML=TABS.map(x=>`<button data-t="${x[0]}" aria-current="${x[0]===t}" onclick="ED=null;tab('${x[0]}')">${x[1]}</button>`).join("");
({painel:pPainel,calendario:pCal,diario:pDia,ciclo:pCiclo,resumo:pRes}[t]||(()=>pList(t)))();
const b=document.querySelector('#stabs [aria-current="true"]');if(b&&b.scrollIntoView)b.scrollIntoView({inline:"center",block:"nearest"})}
function liIt(e){const q=e.k==="documento"?(e.c||"Documento"):KN[e.k];
return `<li class="${e.done?"done":""}"><div><b>${esc(e.t)}</b> <span class="pill">${q}</span><small>${fmt(e.d)}${e.n?" · "+esc(e.n):""}</small></div><span class="acts2">${e.k==="documento"?"":`<button class="lk" onclick="doneIt(${e.id})">${e.done?"Reabrir":"Concluir"}</button><button class="lk" onclick="calOpen('${e.d}')">Calendário</button>`}<button class="lk" onclick="edIt(${e.id})">Editar</button><button class="lk del" onclick="delIt(${e.id})">Excluir</button></span></li>`}
function form(k){const e=(ED&&D.it.find(x=>x.id===ED))||{};
return `<div class="card"><h3>${ED?"Editar":"Novo"} ${k?KN[k].toLowerCase():"compromisso"}</h3>${k?"":`<label for="fk">Tipo</label><select id="fk">${["exame","consulta","vacina","lembrete"].map(x=>`<option value="${x}" ${e.k===x?"selected":""}>${KN[x]}</option>`).join("")}</select>`}
<label for="ft">Nome</label><input id="ft" value="${esc(e.t)}" placeholder="Ex.: Preventivo na UBS"><div class="row"><div><label for="fd">Data</label><input type="date" id="fd" value="${e.d||(k?"":CAL.r)}"></div>${k==="documento"?`<div><label for="fc">Categoria</label><select id="fc">${["Laudo","Receita","Cartão de vacina","Encaminhamento","Outro"].map(x=>`<option ${e.c===x?"selected":""}>${x}</option>`).join("")}</select></div>`:""}</div>
<label for="fn">Observação (opcional)</label><input id="fn" value="${esc(e.n)}"><div class="row"><button class="btn" onclick="saveIt('${k||""}')">${ED?"Salvar alterações":"Salvar"}</button>${ED?`<button class="btn alt" onclick="ED=null;tab(TAB)">Cancelar</button>`:""}</div></div>`}
function saveIt(k){const t=$("ft").value.trim(),d=$("fd").value;if(!t||!d){toast("Preencha o nome e a data.");return}
const o={t,d,n:$("fn").value.trim(),k:k||$("fk").value};if($("fc"))o.c=$("fc").value;
if(ED){Object.assign(D.it.find(x=>x.id===ED),o);ED=null}else D.it.push({...o,id:Date.now(),done:0});
save();toast("Salvo com sucesso.");tab(TAB)}
function edIt(id){ED=id;const e=D.it.find(x=>x.id===id);tab(TAB==="painel"||TAB==="resumo"?e.k:TAB)}
function delIt(id){if(confirm("Excluir este registro? Essa ação não pode ser desfeita.")){D.it=D.it.filter(e=>e.id!==id);save();toast("Registro excluído.");tab(TAB);rHome()}}
function doneIt(id){const e=D.it.find(x=>x.id===id);e.done=e.done?0:1;save();toast(e.done?"Marcado como concluído.":"Reaberto.");tab(TAB);rHome()}
function calOpen(d){CAL.r=d;CAL.v="d";go("saude","calendario")}
const INTRO={exame:"Registre exames feitos ou marcados. Anexos de arquivos não estão disponíveis neste protótipo: guarde nome, data e observações.",consulta:"Consultas marcadas aparecem no calendário e no painel.",vacina:"Anote vacinas tomadas e as que precisa tomar. Consulte o calendário oficial na UBS.",lembrete:"Crie lembretes com data. Este protótipo não envia notificações: os lembretes aparecem aqui e no painel.",documento:"Organize o registro dos seus documentos por categoria. Não há envio de arquivos: registre o nome e onde guardou."};
function pList(k){const l=D.it.filter(e=>e.k===k).sort((a,b)=>a.d.localeCompare(b.d));
$("sbody").innerHTML=`<h2>${KN[k]}s</h2><p>${INTRO[k]}</p>${form(k)}<ul class="list">${l.map(liIt).join("")||`<li>Nenhum ${KN[k].toLowerCase()} cadastrado ainda.</li>`}</ul>`+(k==="exame"?`<div class="note">Quer entender qual exame procurar? Veja <button class="lk" onclick="art('colo')">Câncer do colo do útero e rastreamento</button>.</div>`:"")}
function pPainel(){const n=k=>D.it.filter(e=>e.k===k&&!e.done).length,p=D.it.filter(e=>!e.done&&e.k!=="documento"&&e.d>=today()).sort((a,b)=>a.d.localeCompare(b.d)).slice(0,5),ld=[...D.dia].sort((a,b)=>b.d.localeCompare(a.d))[0];
$("sbody").innerHTML=`<h2>Painel</h2><div class="grid">${[["exame","Exames"],["consulta","Consultas"],["vacina","Vacinas"],["lembrete","Lembretes pendentes"]].map(x=>`<button class="card go" onclick="tab('${x[0]}')"><div class="big">${n(x[0])}</div><h3>${x[1]}</h3></button>`).join("")}</div>
<div class="card"><h3>Próximos compromissos</h3><ul class="list">${p.map(liIt).join("")||"<li>Nenhum compromisso futuro. Comece cadastrando um exame ou uma consulta.</li>"}</ul></div>
<div class="card" style="margin-top:12px"><h3>Último registro no diário</h3><p>${ld?`${fmt(ld.d)}: ${esc(ld.x)}`:"Você ainda não escreveu no diário."}</p></div><div class="row" style="margin-top:12px"><button class="btn" onclick="tab('resumo')">Gerar resumo para consulta</button><button class="btn alt" onclick="go('servicos')">Encontrar um serviço</button></div>`}
function calMove(n){const d=new Date(CAL.r+"T12:00");if(CAL.v==="m"){d.setDate(1);d.setMonth(d.getMonth()+n)}else d.setDate(d.getDate()+n*(CAL.v==="s"?7:1));CAL.r=iso(d);pCal()}
function pCal(){const r=new Date(CAL.r+"T12:00"),v=CAL.v;
let h=`<h2>Calendário</h2><div class="card"><div class="row bar"><button class="btn alt" onclick="calMove(-1)" aria-label="Anterior">‹</button><b>${v==="m"?r.toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):fmt(CAL.r)}</b><button class="btn alt" onclick="calMove(1)" aria-label="Próximo">›</button></div><div class="row bar">${[["d","Dia"],["s","Semana"],["m","Mês"]].map(x=>`<button class="btn ${v===x[0]?"":"alt"}" aria-pressed="${v===x[0]}" onclick="CAL.v='${x[0]}';pCal()">${x[1]}</button>`).join("")}<button class="btn alt" onclick="CAL.r=today();pCal()">Hoje</button></div>`;
const ev=D.it.filter(e=>e.k!=="documento");
if(v==="m"){const y=r.getFullYear(),m=r.getMonth(),f=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate();
h+=`<div class="cal">`+["D","S","T","Q","Q","S","S"].map(x=>`<b aria-hidden="true">${x}</b>`).join("")+"<i></i>".repeat(f);
for(let d=1;d<=n;d++){const s=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,c=ev.filter(e=>e.d===s).length;
h+=`<button class="day ${s===CAL.r?"sel":""} ${s===today()?"hoje":""}" aria-label="${d}, ${c} compromisso(s)" onclick="CAL.r='${s}';pCal()">${d}${c?`<span>${c}</span>`:""}</button>`}h+="</div>"}
const a=v==="s"?add(CAL.r,-r.getDay()):CAL.r,z=v==="s"?add(a,6):CAL.r,l=ev.filter(e=>e.d>=a&&e.d<=z).sort((x,y)=>x.d.localeCompare(y.d));
h+=`</div><h3 style="margin-top:14px">${v==="s"?"Semana de "+fmt(a)+" a "+fmt(z):"Dia "+fmt(CAL.r)}</h3><ul class="list">${l.map(liIt).join("")||"<li>Nada marcado neste período.</li>"}</ul>`+form(null);
$("sbody").innerHTML=h}
function pDia(){const e=D.dia.find(x=>x.id===ED2)||{};
$("sbody").innerHTML=`<h2>Diário de saúde</h2><p>Registre sintomas, sensações e dúvidas para lembrar na consulta. A ELLA não interpreta o que você escreve.</p><div class="card"><label for="dd">Data</label><input type="date" id="dd" value="${e.d||today()}"><label for="dt">O que você quer registrar</label><textarea id="dt" rows="4">${esc(e.x)}</textarea><div class="row"><button class="btn" onclick="saveDia()">${ED2?"Salvar alterações":"Salvar registro"}</button>${ED2?`<button class="btn alt" onclick="ED2=null;pDia()">Cancelar</button>`:""}</div></div><ul class="list">${[...D.dia].sort((a,b)=>b.d.localeCompare(a.d)).map(x=>`<li><div><b>${fmt(x.d)}</b><small>${esc(x.x)}</small></div><span class="acts2"><button class="lk" onclick="ED2=${x.id};pDia()">Editar</button><button class="lk del" onclick="delDia(${x.id})">Excluir</button></span></li>`).join("")||"<li>Nenhum registro ainda.</li>"}</ul>`}
function saveDia(){const d=$("dd").value,x=$("dt").value.trim();if(!d||!x){toast("Preencha a data e o texto.");return}
if(ED2){Object.assign(D.dia.find(e=>e.id===ED2),{d,x});ED2=null}else D.dia.push({id:Date.now(),d,x});save();toast("Registro salvo.");pDia()}
function delDia(id){if(confirm("Excluir este registro do diário?")){D.dia=D.dia.filter(e=>e.id!==id);save();toast("Registro excluído.");pDia()}}
function pCiclo(){$("sbody").innerHTML=`<h2>Meu ciclo</h2><p>Registre o primeiro dia de cada menstruação. Com dois ou mais registros, a ELLA calcula a duração média e estima a próxima.</p><div class="card"><label for="cd">Primeiro dia da menstruação</label><input type="date" id="cd"><button class="btn" onclick="addCy()">Registrar</button></div><div class="card" style="margin-top:12px"><div id="cres"></div></div><ul class="list" id="cys"></ul><div class="note">A previsão é uma estimativa baseada só nos seus registros e não serve como método contraceptivo. Se o ciclo mudar muito ou houver dor forte, procure a UBS. Veja também <button class="lk" onclick="art('dig')">Dignidade menstrual</button>.</div>`;rCy()}
function cyToAg(n){D.it.push({id:Date.now(),k:"lembrete",t:"Menstruação estimada",d:n,n:"",done:0});save();toast("Lembrete criado no calendário.");calOpen(n)}
function pRes(){const q=D.q;$("sbody").innerHTML=`<h2>Resumo para consulta</h2><p>Preencha o que quiser e gere um resumo com seus próximos compromissos, o diário e o ciclo.</p><div class="card"><label for="q1">Motivo da consulta</label><textarea id="q1" rows="2">${esc(q.q1)}</textarea><label for="q3">Medicamentos, alergias e histórico na família</label><textarea id="q3" rows="2">${esc(q.q3)}</textarea><label for="q4">Perguntas para fazer</label><textarea id="q4" rows="2">${esc(q.q4)}</textarea><button class="btn" onclick="genRes()">Gerar resumo</button></div><div id="rres"></div>`}
function genRes(){["q1","q3","q4"].forEach(i=>D.q[i]=$(i).value);save();
const p=D.it.filter(e=>!e.done&&e.k!=="documento"&&e.d>=today()).sort((a,b)=>a.d.localeCompare(b.d)).slice(0,5),h=D.it.filter(e=>e.k==="exame"&&e.d<today()).sort((a,b)=>b.d.localeCompare(a.d)).slice(0,5),dd=[...D.dia].sort((a,b)=>b.d.localeCompare(a.d)).slice(0,5),c=D.cy.length?D.cy[D.cy.length-1]:null;
const t=["RESUMO PARA CONSULTA — feito por mim no ELLA ("+fmt(today())+")","(Registro pessoal, não é documento médico.)","","Motivo: "+(D.q.q1||"—"),"Medicamentos, alergias e histórico: "+(D.q.q3||"—"),"Última menstruação (início): "+(c?fmt(c):"—"),"","Exames já registrados:",...(h.length?h.map(e=>"- "+fmt(e.d)+": "+e.t+(e.n?" ("+e.n+")":"")):["- nenhum"]),"","Próximos compromissos:",...(p.length?p.map(e=>"- "+fmt(e.d)+": "+e.t):["- nenhum"]),"","Anotações do diário:",...(dd.length?dd.map(e=>"- "+fmt(e.d)+": "+e.x):["- nenhuma"]),"","Perguntas: "+(D.q.q4||"—")].join("\n");
$("rres").innerHTML=`<div class="card" style="margin-top:12px"><label for="rt">Resumo (pode editar antes de copiar)</label><textarea id="rt" rows="14">${esc(t)}</textarea><div class="row"><button class="btn" onclick="cpRes()">Copiar</button><button class="btn alt" onclick="window.print()">Imprimir</button></div></div>`;toast("Resumo gerado.")}
function cpRes(){const t=$("rt");t.select();try{(navigator.clipboard?navigator.clipboard.writeText(t.value):Promise.reject()).then(()=>toast("Copiado."),()=>{document.execCommand("copy");toast("Copiado.")})}catch(e){document.execCommand("copy");toast("Copiado.")}}
/* ---- Serviços ---- */
function buscaSv(){const l=$("sl").value.trim();if(!l){toast("Informe o bairro e a cidade.");return}
window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent($("st").value+" "+l),"_blank","noopener")}
const SV={a:"<h3>Unidade Básica de Saúde (UBS)</h3><p>Vá à UBS mais próxima da sua casa. O preventivo é feito lá, por médica(o) ou enfermeira(o), sem custo. Se ainda não tem cadastro, leve documento com foto e comprovante de endereço.</p>",
b:"<h3>UBS, o quanto antes</h3><p>Corrimento, odor forte e lesões ou verrugas na vulva ou vagina devem ser avaliados na atenção primária o mais rápido possível. A equipe examina, trata e encaminha ao especialista se for preciso.</p>",
c:"<h3>UBS</h3><p>Vacinas do calendário (incluindo HPV) e preservativos masculinos e femininos estão disponíveis nas unidades de atenção primária. <a href='https://www.gov.br/saude/pt-br/vacinacao/calendario' target='_blank' rel='noopener'>Ver calendário</a>.</p>",
d:"<h3>UBS: pré-natal</h3><p>Toda mulher tem direito a atendimento na gravidez, no parto e após o parto. Procure a UBS para começar o pré-natal. Em sangramento, dor forte ou febre, vá a uma UPA ou ligue 192. <a href='https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-da-mulher/saude-materna' target='_blank' rel='noopener'>Saúde materna</a>.</p>",
e:"<h3>Peça ajuda agora</h3><p>Perigo imediato: <b>190</b>. Orientação e denúncia: <b>Ligue 180</b>. Violência sexual: procure UBS ou hospital, onde há atendimento de saúde. <a href='#' onclick=\"go('apoio');return false\">Ver página de apoio</a>.</p>",
f:"<h3>UBS, CAPS ou CVV</h3><p>Para conversar agora, ligue <b>188</b> (CVV). Para acompanhamento, comece pela UBS, que pode encaminhar ao CAPS. Em risco imediato, ligue 192.</p>",
h:"<h3>Vá a uma UPA ou hospital</h3><p>Sangramento, dor forte, febre ou tontura na gravidez precisam de avaliação rápida. Ligue 192 (SAMU) se estiver muito mal. Você tem direito a atendimento sem julgamento. <a href='#' onclick=\"go('gestacao');return false\">Saiba mais</a>.</p>",
g:"<h3>Volte à UBS que pediu o exame</h3><p>Leve o resultado. Repetição de exame, colposcopia ou outros passos dependem do laudo, e quem decide é a equipe de saúde. Registre o retorno na sua Agenda.</p>"};
function showSv(){$("svr").innerHTML=SV[$("sit").value]||"Escolha uma situação para ver o próximo passo."}

function addCy(){const d=$("cd").value;if(!d)return;if(!D.cy.includes(d))D.cy.push(d);D.cy.sort();save();rCy()}
function delCy(d){D.cy=D.cy.filter(x=>x!==d);save();rCy()}
function rCy(){const c=D.cy;let h="Nenhum registro ainda.";
if(c.length===1)h="Registre mais um início de menstruação para calcular seu ciclo.";
if(c.length>1){const g=[];for(let i=1;i<c.length;i++)g.push(Math.round((new Date(c[i])-new Date(c[i-1]))/864e5));
const m=Math.round(g.reduce((a,b)=>a+b,0)/g.length);const n=new Date(new Date(c[c.length-1]+"T12:00").getTime()+m*864e5).toISOString().slice(0,10);
h=`<div class="big">${m} dias</div>duração média do ciclo (${g.length} ${g.length>1?"ciclos":"ciclo"}).<br>Próxima menstruação estimada: <b>${fmt(n)}</b>.<br><button class="btn alt" onclick="cyToAg('${n}')">Criar lembrete na agenda</button>`}
$("cres").innerHTML=h;
$("cys").innerHTML=[...c].reverse().map(d=>`<li><span>${fmt(d)}</span><button class="x" aria-label="Apagar ${fmt(d)}" onclick="delCy('${d}')">×</button></li>`).join("")}

/* ---- Início ---- */
$("nav").innerHTML=V.map(v=>`<button data-v="${v[0]}" onclick="go('${v[0]}')">${v[1]}</button>`).join("");
document.querySelectorAll(".emb-slot").forEach(e=>e.innerHTML=emblem());
document.querySelectorAll("[data-lib]").forEach(e=>e.innerHTML=cards(e.dataset.lib));
$("atalhos").innerHTML=V.slice(1).map(v=>`<button class="card go" onclick="go('${v[0]}')"><h3>${v[1]}</h3><p>${{saude:"Calendário, exames, lembretes, diário e resumo para consulta.",prevencao:"Rastreamento, endometriose, coração, ossos e mais.",sexual:"ISTs, testagem, contracepção e consentimento.",apoio:"Bem-estar emocional, violência e telefones de ajuda.",trans:"Acesso, acompanhamento e direitos no SUS.",servicos:"Qual serviço procurar e como encontrar perto de você.",conteudos:"Biblioteca com busca, categorias e fontes oficiais."}[v[0]]}</p></button>`).join("");
go("inicio");
